export const siteConfig = {
  name: "New Bodies Gym",
  motto: "Where everyone is welcome",
  description: "A high-performance gym facility in Buxton featuring Olympic equipment, cardio suites, and diverse classes.",
  contact: {
    address: {
      line1: "Unit 6, Tongue Lane Ind. Estate",
      city: "Buxton",
      postcode: "SK17 7LF",
    },
    phone: "01298 72006",
    email: "newbodiesgym@hotmail.co.uk",
  },
  openingHours: [
    { day: "Monday", open: "06:00", close: "21:30" },
    { day: "Tuesday", open: "06:00", close: "21:30" },
    { day: "Wednesday", open: "06:00", close: "21:30" },
    { day: "Thursday", open: "06:00", close: "21:30" },
    { day: "Friday", open: "06:00", close: "20:00" },
    { day: "Saturday", open: "09:00", close: "15:00" },
    { day: "Sunday", open: "09:00", close: "15:00" },
    { day: "Bank Holidays", open: "09:00", close: "15:00" },
  ],
  facilities: [
    "Large Mixed Gyms",
    "Ladies Only Zone",
    "Cardio Suites",
    "Fully Equipped Olympic Gym",
    "Power Zone",
    "Full Range Resistance Machines",
    "Free Weights",
    "Boxing Studio",
    "Virtual Spin Studio",
    "Fitness Studio",
    "Personal Training",
    "Easyline Circuit",
    "Protein & Smoothie Bar",
    "Sundome",
    "Changing & Shower Facilities",
    "Free Parking",
    "Coffee Machine",
    "Calisthenics Zone",
  ],
  rules: [
    "Gym open and everyone welcome.",
    "Please follow guidance to book a studio class. Booking is not essential to use the gym.",
    "Valid live membership required to book classes via the link.",
    "Non-members welcome - call to book a class.",
    "Train safely, return equipment, and respect others.",
    "Most of all, enjoy your training.",
  ]
};